import Foundation

/// Renders the two sigil-fenced regions in aerospace.toml from spaces.json:
/// the digit-bindings block (inside `[mode.main.binding]`) and the
/// assignment block (top-level, emits `[workspace-to-monitor-force-
/// assignment]`). Each region has its own fence pair so `merge` can
/// update them independently.
///
/// Library target (not part of the ws-topology executable) so the tests
/// exercise the production implementation rather than a mirror copy.
public enum AerospaceFragment {

    public static let openFence  = "# >>> sigil generated >>>"
    public static let closeFence = "# <<< sigil generated <<<"

    public static let assignmentOpenFence  = "# >>> sigil generated: assignments >>>"
    public static let assignmentCloseFence = "# <<< sigil generated: assignments <<<"

    /// Digit bindings `cmd-alt-ctrl-shift-1..0` for the first 10 slots.
    /// Slot 10 wraps to `'0'`. Must sit inside `[mode.main.binding]`;
    /// emits no table header to avoid TOML's no-redefine rule.
    public static func render(slotNames: [String]) -> String {
        let visible = Array(slotNames.prefix(10))
        var lines: [String] = []
        lines.append(openFence)
        lines.append("# Generated by `ws-topology emit-aerospace`. Hand-edits inside")
        lines.append("# this block are clobbered on next regeneration. Edit the source")
        lines.append("# of truth in ~/.config/workspace/spaces.json (and re-emit) or")
        lines.append("# the user-owned section of aerospace.toml (above the fence).")
        lines.append("#")
        lines.append("# This block must live inside an open [mode.main.binding] table —")
        lines.append("# do not move it above any [...] header.")

        if visible.isEmpty {
            lines.append("# (no workspaces declared in spaces.json yet)")
        } else {
            lines.append("# Hyper+digit: focus workspace by name. Digit N → N-th workspace")
            lines.append("# in spaces.json composite-key order. Slot 10 is bound to '0'.")
            for (i, name) in visible.enumerated() {
                let digit = (i == 9) ? "0" : String(i + 1)
                lines.append("cmd-alt-ctrl-shift-\(digit) = \"workspace \(escapeTOMLBasicString(name))\"")
            }
            lines.append("# Send-window digit bindings (Caps+Shift+N) intentionally absent —")
            lines.append("# Hyperkey collapses Caps+Shift+digit into Caps+digit (same chord).")
            lines.append("# Use Caps+f (ws-prompt send) to send a window to a specific workspace.")
        }
        lines.append(closeFence)
        return lines.joined(separator: "\n") + "\n"
    }

    /// `[workspace-to-monitor-force-assignment]` table. Top-level; emits
    /// its own table header. Every slot pins to monitor 1 — when v3
    /// spaces.json gains real displayUUID → ordinal resolution, thread
    /// it through here.
    public static func renderAssignmentBlock(slotNames: [String]) -> String {
        var lines: [String] = []
        lines.append(assignmentOpenFence)
        lines.append("# Generated by `ws-topology emit-aerospace`. Hand-edits inside")
        lines.append("# this block are clobbered on next regeneration. Edit the source")
        lines.append("# of truth in ~/.config/workspace/spaces.json (and re-emit).")
        lines.append("#")
        lines.append("# Workspace existence + monitor binding. Each name MUST match a")
        lines.append("# spaces.json slot's workspaceName; mismatches cause aerospace")
        lines.append("# chords (`workspace N`) to fail silently.")
        if slotNames.isEmpty {
            lines.append("# (no workspaces declared in spaces.json yet)")
        } else {
            lines.append("[workspace-to-monitor-force-assignment]")
            for name in slotNames {
                lines.append("\"\(escapeTOMLBasicString(name))\" = 1")
            }
        }
        lines.append(assignmentCloseFence)
        return lines.joined(separator: "\n") + "\n"
    }

    /// Escape for a TOML basic (double-quoted) string. Both generated
    /// blocks render names inside `"…"` — TOML literal strings (`'…'`)
    /// support no escapes at all, so a name containing a quote can only
    /// be represented in basic-string form.
    public static func escapeTOMLBasicString(_ s: String) -> String {
        var out = ""
        out.reserveCapacity(s.count)
        for ch in s.unicodeScalars {
            switch ch {
            case "\"":  out += "\\\""
            case "\\":  out += "\\\\"
            case "\n":  out += "\\n"
            case "\r":  out += "\\r"
            case "\t":  out += "\\t"
            default:
                if ch.value < 0x20 {
                    out += String(format: "\\u%04X", ch.value)
                } else {
                    out += String(ch)
                }
            }
        }
        return out
    }

    public enum MergeError: Error, CustomStringConvertible, Equatable {
        /// An open fence with no matching close fence. Appending a fresh
        /// block would pair the orphan with the new block's close fence
        /// on the NEXT merge and clobber every user line in between, so
        /// the merge refuses instead.
        case unterminatedFence(open: String)

        public var description: String {
            switch self {
            case .unterminatedFence(let open):
                return "found open fence '\(open)' with no matching close fence — repair aerospace.toml before re-emitting"
            }
        }
    }

    /// Replace lines between the fence pair (inclusive) with `block`, or
    /// append at EOF if absent. Idempotent. Line-anchored — fences must
    /// appear as standalone lines, not as substrings in doc comments
    /// (the regression test pins this).
    public static func merge(
        block: String,
        into existing: String,
        openFence: String = AerospaceFragment.openFence,
        closeFence: String = AerospaceFragment.closeFence
    ) throws -> String {
        // Trim block trailing newline; we'll re-add one when appending.
        let cleanBlock = block.hasSuffix("\n") ? String(block.dropLast()) : block

        var lines = existing.components(separatedBy: "\n")
        // After split, a trailing "\n" in input produces an empty last
        // element. Track + restore so output preserves the trailing
        // newline state.
        let hadTrailingNewline = existing.hasSuffix("\n")
        if hadTrailingNewline, lines.last == "" { lines.removeLast() }

        let openIdx = lines.firstIndex(where: { $0.trimmingCharacters(in: .whitespaces) == openFence })
        let closeIdx: Int? = openIdx.flatMap { o in
            lines[(o + 1)...].firstIndex(where: { $0.trimmingCharacters(in: .whitespaces) == closeFence })
        }

        if let o = openIdx, let c = closeIdx {
            // Replace lines [o ... c] (inclusive) with the new block lines.
            let blockLines = cleanBlock.components(separatedBy: "\n")
            lines.replaceSubrange(o...c, with: blockLines)
            var out = lines.joined(separator: "\n")
            if hadTrailingNewline || !out.hasSuffix("\n") { out += "\n" }
            return out
        }

        if openIdx != nil {
            throw MergeError.unterminatedFence(open: openFence)
        }

        // No fence found — append. Add a separator newline if the file
        // doesn't end in one.
        let needsSeparator = !existing.isEmpty && !existing.hasSuffix("\n")
        return existing + (needsSeparator ? "\n" : "") + cleanBlock + "\n"
    }
}
