import AdaptersAppKit
import DisplayTopology
import Foundation
import LayoutPolicy

/// Renders `~/.cache/workspace/layout.env` — a shell-sourceable view of the
/// per-display layout policy, designed for jq-less consumption by the
/// SketchyBar plugins. Keys are stable so `notch-detect.sh`,
/// `per-display-pills.sh`, and `recenter.sh` can `source` it and read the
/// values directly.
enum LayoutEnvRenderer {
    static func render(
        snapshot: TopologySnapshot,
        policies: LayoutPolicySet,
        accessibility: AccessibilityState
    ) -> String {
        var lines: [String] = []
        lines.append("# Generated by ws-topologyd. Do not edit by hand.")
        lines.append("# Re-source on workspace_changed; values reflect the latest topology.")
        lines.append("")

        // Identify the laptop display and whether it has a notch.
        let laptop = snapshot.displays.first(where: \.isBuiltIn)
        let laptopID = laptop?.id ?? snapshot.primaryDisplayID
        let laptopHasNotch = laptop.map { $0.safeAreaInsets.top > 0 } ?? false

        lines.append("export WS_LAPTOP_DISPLAY_ID=\(laptopID)")
        lines.append("export WS_LAPTOP_HAS_NOTCH=\(laptopHasNotch ? "yes" : "no")")
        lines.append("export WS_PRIMARY_DISPLAY_ID=\(snapshot.primaryDisplayID)")
        lines.append("")

        // Accessibility flags.
        lines.append("export WS_REDUCE_MOTION=\(accessibility.reduceMotion ? "1" : "0")")
        lines.append("export WS_INCREASE_CONTRAST=\(accessibility.increaseContrast ? "1" : "0")")
        lines.append("")

        // Per-display detail. Keyed by display ID so shell readers can look up
        // `WS_MAX_VISIBLE_SLOTS_${WS_LAPTOP_DISPLAY_ID}`, etc.
        for policy in policies.policies {
            let id = policy.displayID
            lines.append("# display \(id) — \(policy.layoutClass.rawValue)")
            lines.append("export WS_LAYOUT_CLASS_\(id)=\(policy.layoutClass.rawValue)")
            lines.append("export WS_MAX_VISIBLE_SLOTS_\(id)=\(policy.maxVisibleSlots)")
            lines.append("export WS_BAR_HEIGHT_PT_\(id)=\(formatPoint(policy.barHeightPoints))")
            lines.append("export WS_PILL_AVG_WIDTH_PT_\(id)=\(formatPoint(policy.pillAverageWidthPoints))")
            lines.append("export WS_DENSITY_MULTIPLIER_\(id)=\(formatPoint(policy.ornamentDensityMultiplier))")
            lines.append("export WS_USE_AUX_TOP_\(id)=\(policy.shouldUseAuxiliaryTopAreas ? "1" : "0")")
            lines.append("export WS_MIRROR_SECONDARY_\(id)=\(policy.isCollapsedMirrorSecondary ? "1" : "0")")
            lines.append("export WS_TOP_REGION_X_\(id)=\(formatPoint(policy.topOrnamentRegion.minX))")
            lines.append("export WS_TOP_REGION_Y_\(id)=\(formatPoint(policy.topOrnamentRegion.minY))")
            lines.append("export WS_TOP_REGION_W_\(id)=\(formatPoint(policy.topOrnamentRegion.width))")
            lines.append("export WS_TOP_REGION_H_\(id)=\(formatPoint(policy.topOrnamentRegion.height))")

            // Notched-only: right aux + notch coordinates. recenter.sh
            // uses these for the "centered, split symmetrically around
            // the notch" anchor strategy.
            if let auxRight = policy.auxiliaryTopRightRegion {
                lines.append("export WS_TOP_REGION_RIGHT_X_\(id)=\(formatPoint(auxRight.minX))")
                lines.append("export WS_TOP_REGION_RIGHT_W_\(id)=\(formatPoint(auxRight.width))")
            }
            if let notch = policy.notchRegion {
                lines.append("export WS_NOTCH_X_\(id)=\(formatPoint(notch.minX))")
                lines.append("export WS_NOTCH_W_\(id)=\(formatPoint(notch.width))")
            }

            if let fb = policy.fallbackScreenIDOnDisconnect {
                lines.append("export WS_FALLBACK_SCREEN_ID_\(id)=\(fb)")
            }
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private static func formatPoint(_ value: Double) -> String {
        // Trim trailing zeros for compactness. Shell consumers do integer math
        // on these via `${value%.*}` already in the existing plugins.
        let rounded = (value * 100).rounded() / 100
        if rounded == rounded.rounded() {
            return String(Int(rounded))
        }
        return String(format: "%.2f", rounded)
    }
}
